### ISSUE TITLE
please help me. Why do I unzip the entire file and appear " __Unknown"

### ISSUE THREAD

**Issue by nonamebatbai** [Ekey/MNK.LPKG.Tool#2]
![image](https://user-images.githubusercontent.com/55612825/157573020-2234f555-dda6-4b2f-a463-431c83660909.png)

**Comment by Essentionesque** [comment]
There will still be various "__Unknown" things BUT. The warning that the console gives you should be the main indicator. Wherever you have the EXE build of the script, you need to copy the "Projects" folder over to. Like this.
![image](https://user-images.githubusercontent.com/81198808/158481490-00ee6b9b-196f-48a6-b477-9fe9232920ab.png)
That way you'll be able to see the different names of the files and folders that don't end up as __Unknown.

**Comment by nonamebatbai** [comment]
> There will still be various "__Unknown" things BUT. The warning that the console gives you should be the main indicator. Wherever you have the EXE build of the script, you need to copy the "Projects" folder over to. Like this. ![image](https://user-images.githubusercontent.com/81198808/158481490-00ee6b9b-196f-48a6-b477-9fe9232920ab.png) That way you'll be able to see the different names of the files and folders that don't end up as __Unknown. As for the ones that end up as __Unknown, I'll see what I can do if it's possible.

can you show me your cmd script to extract the file . I still can't do it

**Comment by Ekey** [comment]
The files in the __Unknown folder is unknown files for which their real names have not been found. 

@[nonamebatbai](https://github.com/nonamebatbai) - You are correctly using the app, you just forgot to copy the Project folder with names list. Look the screenshot of how it should be.

**Comment by nonamebatbai** [comment]
thank you guys. I did it

**Comment by nonamebatbai** [comment]
![image](https://user-images.githubusercontent.com/55612825/159195499-fa817d3a-f388-4a0e-bbac-00657b0a48d7.png)
 so the game's text file is a file with the extension ".mbb" . Do you have a tool to export and import it?

**Comment by Ekey** [comment]
> Do you have a tool to export and import it?

Nope.

**Comment by foubou** [comment]
@nonamebatbai : If you find tools to export and import the .mbb files, please let me know !
I'll keep you posted if I find anything too.
@Essentionesque I found someone talking about lgx archives on, Zenhax. He is working on a tool to extract models I guess.
https://forum.xentax.com/viewtopic.php?f=16&t=19249&p=182555&hilit=MONARK#p182555
