### ISSUE TITLE
I extracted everything, where do I go from here?

### ISSUE THREAD

**Issue by Essentionesque** [Ekey/MNK.LPKG.Tool#3]
It's hard to tell since I don't know what engine the game is on (which would've most likely helped in figuring things out). I figured I'd ask here since this tool is, like, the first step.

The main files formats, at least in terms of what I'm looking for, are...

- LGX
- LCCHAIN
- CSV
- LCANIPK

Examples:
![image](https://user-images.githubusercontent.com/81198808/158488346-b0b3cc10-8454-4d44-96c4-430894d057bd.png)
![image](https://user-images.githubusercontent.com/81198808/158488848-9c541492-cf7c-4eb6-a0c2-8aa8a1ea693b.png)

I wanna be able to view the model files and hopefully convert them into more usable formats...

**Comment by Ekey** [comment]
Idk about models but you can try to ask it on Xentax or Zenhax forums.

https://forum.xentax.com/viewforum.php?f=16
https://zenhax.com/viewforum.php?f=5

**Comment by foubou** [comment]
@Essentionesque I found someone talking about lgx archives on, Zenhax. He is working on a tool to extract models I guess.
https://forum.xentax.com/viewtopic.php?f=16&t=19249&p=182555&hilit=MONARK#p182555
